# Generated by Django 2.1.5 on 2019-01-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dombrusapp', '0002_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('Br', 'Брусовые'), ('Ka', 'Каркасные'), ('Ba', 'Бани')], max_length=2),
        ),
    ]
