# Generated by Django 2.1.5 on 2019-01-28 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dombrusapp', '0003_auto_20190128_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='description',
        ),
        migrations.AddField(
            model_name='contact',
            name='title',
            field=models.CharField(default='Контакт', max_length=200),
        ),
        migrations.AddField(
            model_name='contact',
            name='value',
            field=models.CharField(default='Значение', max_length=200),
        ),
    ]
