# Generated by Django 2.1.5 on 2019-02-01 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dombrusapp', '0005_auto_20190130_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='title',
            field=models.CharField(default='Пример: телефон', max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='value',
            field=models.CharField(default='Пример: +7 555 123-12-12', max_length=200, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_main_page',
            field=models.BooleanField(default=False, verbose_name='На главной'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='project',
            name='photo_1',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Главное фото'),
        ),
        migrations.AlterField(
            model_name='project',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='project',
            name='size',
            field=models.CharField(max_length=200, verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('Br', 'Брусовые'), ('Ka', 'Каркасные'), ('Ba', 'Бани')], max_length=2, verbose_name='Тип'),
        ),
    ]
